# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstaInfo', '0001_initial'),
        ('Prevent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InstaInfo.InstaInfo')),
                ('prevent_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prevent.Prevent')),
            ],
        ),
        migrations.AddField(
            model_name='prevent',
            name='insta_info',
            field=models.ManyToManyField(through='Prevent.PreventMembership', to='InstaInfo.InstaInfo'),
        ),
    ]
