# Generated by Django 2.0.1 on 2018-03-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prevent', '0002_auto_20170831_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prevent',
            options={},
        ),
        migrations.AlterModelTable(
            name='prevent',
            table='Prevent',
        ),
    ]
