# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InstaInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.CharField(max_length=255, unique=True, verbose_name='MESSAGE_CONTENT')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='CREATE_DATE')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='MODIFY_DATE')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'db_table': 'MESSAGE',
            },
        ),
        migrations.CreateModel(
            name='MessageMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InstaInfo.InstaInfo')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Message.Message')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='insta_info',
            field=models.ManyToManyField(through='Message.MessageMembership', to='InstaInfo.InstaInfo'),
        ),
    ]
