# Generated by Django 2.0.1 on 2018-03-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
    ]
