# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstaInfo', '0001_initial'),
        ('ActivityLog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='owner',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='insta_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InstaInfo.InstaInfo'),
        ),
    ]
