# Generated by Django 2.0.1 on 2018-03-31 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityLog', '0003_remove_activitylog_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={},
        ),
        migrations.AlterModelTable(
            name='activitylog',
            table=None,
        ),
    ]
