# Generated by Django 2.0.1 on 2018-03-31 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityLog', '0004_auto_20180401_0147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ('-create_date',)},
        ),
        migrations.AlterModelTable(
            name='activitylog',
            table='ActivityLog',
        ),
    ]
