# Generated by Django 2.0.1 on 2018-03-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityLog', '0005_auto_20180401_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='img_url',
        ),
    ]
