# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, unique=True, verbose_name='TAG_NAME')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='CREATE_DATE')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='MODIFY_DATE')),
            ],
            options={
                'verbose_name': 'hashtag',
                'verbose_name_plural': 'hashtags',
                'db_table': 'HASHTAG',
            },
        ),
    ]
