# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstaInfo', '0001_initial'),
        ('HashTag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasgTagMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='CREATE_DATE')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='MODIFY_DATE')),
                ('hash_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HashTag.HashTag')),
                ('insta_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InstaInfo.InstaInfo')),
            ],
        ),
        migrations.AddField(
            model_name='hashtag',
            name='insta_info',
            field=models.ManyToManyField(through='HashTag.HasgTagMembership', to='InstaInfo.InstaInfo'),
        ),
    ]
