# Generated by Django 2.0.1 on 2018-03-31 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HashTag', '0002_auto_20170831_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashtag',
            options={},
        ),
        migrations.AlterModelTable(
            name='hashtag',
            table='HashTag',
        ),
    ]
