# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 16:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_account', models.CharField(max_length=50, unique=True, verbose_name='INSTA_ACCOUNT')),
                ('insta_passwd', models.CharField(max_length=50, verbose_name='INSTA_PASSWD')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='CREATE_DATE')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='MODIFY_DATE')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'instainfo',
                'verbose_name_plural': 'instainfos',
                'db_table': 'INSTAINFO',
            },
        ),
    ]
