# Generated by Django 2.0.1 on 2018-03-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instainfo',
            name='onoff_trigger',
            field=models.BooleanField(default=False, verbose_name='ONOFF_TRIGGER'),
        ),
    ]
