# Generated by Django 2.0.1 on 2018-03-31 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstaInfo', '0002_instainfo_onoff_trigger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instainfo',
            options={},
        ),
        migrations.AlterModelTable(
            name='instainfo',
            table='InstaInfo',
        ),
    ]
