# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InstaInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_count', models.CharField(max_length=50, verbose_name='FOLLOW_COUNT')),
                ('follower_count', models.CharField(max_length=50, verbose_name='FOLLOWER_COUNT')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='CREATE_DATE')),
                ('insta_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InstaInfo.InstaInfo')),
            ],
            options={
                'verbose_name': 'countlog',
                'verbose_name_plural': 'countlogs',
                'db_table': 'COUNTLOG',
            },
        ),
    ]
