# Generated by Django 2.0.1 on 2018-03-31 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CountLog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countlog',
            options={},
        ),
        migrations.AlterModelTable(
            name='countlog',
            table='CountLog',
        ),
    ]
