# Generated by Django 2.0.4 on 2018-04-09 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CountLog', '0002_auto_20180401_0147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countlog',
            options={'ordering': ('-create_date',)},
        ),
    ]
